require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-sequel

AllCops:
  TargetRubyVersion: 3.3.1
  EnabledByDefault: true

#################### Bundler ##############################

Bundler/GemComment:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

#################### Styles ################################

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false
